### ISSUE TITLE
Prune nonterminals and terminals not reachable from the start state of the grammar, also report as warnings

### ISSUE THREAD

**Issue by mewmew** [inspirer/textmapper#16]
In relation to #15, it would also be useful if Textmapper output warnings when a grammar contained unused rules, that is, rules that cannot be reached from the start state of the grammar.

Consider the follow grammar ([qux.tm](https://github.com/mewspring/foo/blob/master/qux/qux.tm)):

```c
language qux(go);

lang = "qux"
package = "github.com/mewspring/foo/qux"

:: lexer

'foo' : /foo/
'bar' : /bar/

:: parser

input : Foo ;

Foo : 'foo' ;

Bar : 'bar' ;
```

`Bar` is not reachable from `input`, thus the non-terminal `Bar` can be pruned from the [parser table](https://github.com/mewspring/foo/blob/master/qux/parser_tables.go#L15). This step could be performed automatically by Textmapper when generating the parser tables.

To check which states are reachable, a depth-first search from the start state of the grammar could be used as an initial implementation.

While pruning non-terminals, it would be very useful if this information was presented as warnings to the user. Both as they may then refine and simplify their grammar. Or perhaps just as likely, discover bugs where rules were not used, even though that was the intention of the user.

Similarly, tokens (e.g. `bar`) may be pruned from the [list of tokens](https://github.com/mewspring/foo/blob/master/qux/token.go#L29), and the [lexer table](https://github.com/mewspring/foo/blob/master/qux/lexer_tables.go) may be refined to exclude tokens that are not present in any rule that is reachable from the start state of the grammar.

**Edit:**
Current output of Textmapper for `qux.tm`:

```
$ textmapper
lalr: 0.013s, text: 0.072s, parser: 5 states, 0KB
```

Suggested output of Textmapper when pruning non-terminals and terminals:

```
$ textmapper
warning: nonterminal Bar not reachable from input state, it has been pruned
warning: terminal bar not reachable from input state, it has been pruned
lalr: 0.012s, text: 0.08s, parser: 5 states, 0KB
```

Or something along those lines.

**Comment by inspirer** [comment]
There is an option to make Textmapper complain about unreachable symbols but if we make it on by default, the output will be quite noisy during the initial grammar development. Converting grammars to LALR(1) is hard and we don't want to make this experience even worse. I plan to write an article about best practices for the conversion process and it involves keeping the grammar broken for a long time.

The symbols are pruned from the actual parsing tables and don't take up space because of the table compression used. I still generate various constants for them. This is likely to change with the rewrite of Textmapper in Go.

```
$ textmapper -d && cat errors
lalr: 0.017s, text: 0.094s, parser: 5 states, 0KB
symbol `invalid_token` is useless
qux.tm,9: symbol `'bar'` is useless
qux.tm,17: symbol `Bar` is useless
```

**Comment by mewmew** [comment]
Thanks! The `-d` option is basically what I was looking for.
