### ISSUE TITLE
Potential optimization for listener.go, use ... notation to use arrays instead of slices for interface types

### ISSUE THREAD

**Issue by mewmew** [inspirer/textmapper#22]
For interface (i.e. set/union types), lookup tables are generated to be used by selector.go. These lookup tables are currently generated as slices.

Since the size of the lookup tables is fixed, it should be possible to use the `[...]` notation to allocate arrays of the required size to keep all elements of the array literals.

From generated `listener.go`
```diff
-var Type = []NodeType{
+var Type = [...]NodeType{
 	ArrayType,
 	FloatType,
 	FuncType,
 	IntType,
 	LabelType,
 	MMXType,
 	MetadataType,
 	NamedType,
 	PackedStructType,
 	PointerType,
 	StructType,
 	TokenType,
 	VectorType,
 	VoidType,
 }
```

Used in `selector.go`:

```go
	Type                            = OneOf(ll.Type...)
```

Potentially this could remove a few bounds checks.

However, as I'm writing this, it seem more likely that these lookup tables are *always* used as slices (e.g. passed as an argument to `OneOf`. Therefore, having them as slices, and not arrays makes more sense, as otherwise we would have to generate slice descriptors for each invocation to `OneOf`.

Well, feel free to close this issue. I just wanted to write it down, so we can evaluate or discard the idea.

Cheers,
Robin

**Comment by inspirer** [comment]
Yeah, thanks for giving this an extra thought. I'm not pursuing any optimizations in this area since this is startup code and it is not worth optimizing. Another activity I'm looking forward in this space is an llvm backend for Go, which should be awesome at inlining and dead code elimination. I also think read-only slice detection can be easily added to the compiler even without llvm. I haven't checked the generated code with Go 1.11, which is hopefully better than before.

**Comment by mewmew** [comment]
> Another activity I'm looking forward in this space is an llvm backend for Go, which should be awesome at inlining and dead code elimination.

Most definitely, also looking forward to this!

> Yeah, thanks for giving this an extra thought. I'm not pursuing any optimizations in this area since this is startup code and it is not worth optimizing.

That's fair. Closing the issue as it's working as intended.

**Comment by inspirer** [comment]
I tried to apply this idea to the main bottleneck of all large grammars - the gotoState function, which does a lookup and a binary search in two static arrays of numbers. The assembly code looks better with arrays instead of slices (the sizes become simple constants, plus we get rid of one indirection) but the overall performance on the Javascript benchmark gets worse. I'm very curious to know why... The only idea I have so far is that it somehow changes the alignment of code/data, and so this effect is local and should be ignored. I'll try measure more to (hopefully) confirm this.

If you have a good benchmark for your grammar, try to replace all [] with [...] in parser_tables.go and let me know if it gets better for you.

btw I've experimented with various optimizations of the gotoState function, and there are some low hanging fruits there. By throwing in ~10Mb of RAM I can speed up parsing "minified" Javascript from 12 to 21 MB/s (good for server-side use-cases, bad for the binary startup time). I have two other optimizations that each get me to ~14 MB/s: 1) reordering elements so that binary search always jumps forward, and 2) using a bit rank data-structure as a foundation for a fast sparse map (this one seems a bit heavy). I also want to experiment with an in-memory B-tree like structure with 64 bytes per node (to make full use of cache lines). It should be possible to generate a perfect B-tree with pretty good lookup time.

For now I'm struggling to make use of bounds-check elimination logic. It is quite simplistic in Go, and I have 4 checks in the gotoState function ;(  See https://go.googlesource.com/go/+/master/test/prove.go
