### ISSUE TITLE
Unable to parse grammar with unordered sequences using ampersand (‘&’) operator

### ISSUE THREAD

**Issue by mewmew** [inspirer/textmapper#8]
I tried to use the ampersand operator to handle unordered sequences, but when I try to generate the parser, Textmapper reports a syntax error. Is unordered sequences still supported by Textmapper?

```
$ java -jar ${TM_DIR}/tm-tool/libs/textmapper-0.9.21.jar a.tm 
a.tm,17: syntax error before line 17
```

For the following grammar:

```
language foobar(go);

lang = "foobar"
package = "github.com/mewmew/foobar"

::lexer

'foo' : /foo/
'bar' : /bar/
'baz' : /baz/

::parser

input : ABC ;

# accepts all permutations of A, B and C as well as an empty string
ABC : (A & B & C)? ;

A : 'foo' ;
B : 'bar' ;
C : 'baz' ;
```

**Comment by inspirer** [comment]
Yes, I removed unordered sequences a year ago to simplify the grammar. They were not very useful/used since most of the time one wants to allow duplicates of A, B, and C, and so uses a list. The also didn't play very well with the new event-based way of building ASTs (using the arrow notation), so I gave up.

I'll clean up the documentation tomorrow.

**Comment by mewmew** [comment]
> Yes, I removed unordered sequences a year ago to simplify the grammar. They were not very useful/used since most of the time one wants to allow duplicates of A, B, and C, and so uses a list. The also didn't play very well with the new event-based way of building ASTs (using the arrow notation), so I gave up.

Thanks for the added rationale. I was glad to find them in the Language Reference, as they do solve a concrete problem in grammars. However, I understand if you don't think they carry their own weight, and if they did not interact well with the event-based way of building ASTs, then having them gone is not a huge loss.

> I'll clean up the documentation tomorrow.

Thanks!

Speaking of which, and re:

> I will refresh the documentation in the upcoming weeks to better cover Textmapper advanced features, such as templates, grammar lookaheads, token sets, error recovery best practices, and the arrow notation for producing ASTs.

I very much look forward to added documentation on best practices for constructing ASTs. I now have a [Textmapper grammar for LLVM IR](https://github.com/mewmew/l-tm/blob/master/parser/ll.tm) that is capable of parsing the entire language, but have not yet figure out how to produce the AST.

**Comment by inspirer** [comment]
To wrap up this thread: instead of `ABC : (A & B & C)? ;`, I'd write `ABC: (A | B | C)*` which accepts a broader set of input strings, and then add a semantic check to the code processing the parsed AST.

Regarding the AST construction - I don't like writing lots of semantic actions in the grammar as it makes the file way less readable, and instead prefer reporting all interesting nodes with ranges using the arrow notation, and then reconstructing the AST from this stream. See https://github.com/inspirer/textmapper/tree/master/tm-parsers/tm

**Comment by mewmew** [comment]
> To wrap up this thread: instead of ABC : (A & B & C)? ;, I'd write ABC: (A | B | C)* which accepts a broader set of input strings, and then add a semantic check to the code processing the parsed AST.

Thanks. This is the approach I also ended up using in https://github.com/mewmew/l-tm/blob/master/parser/ll.tm#L4068

```c
OverflowFlags
	: ('nsw' | 'nuw')*
;
```

> Regarding the AST construction - I don't like writing lots of semantic actions in the grammar as it makes the file way less readable, and instead prefer reporting all interesting nodes with ranges using the arrow notation, and then reconstructing the AST from this stream. See https://github.com/inspirer/textmapper/tree/master/tm-parsers/tm

I still have to wrap my head around exactly how this works. Thanks for the note though! I'll keep a close eye when http://textmapper.org/documentation.html#abstract-syntax-tree is updated.
